// Generated by gencpp from file rosorbitcamera/Int32Numpy.msg
// DO NOT EDIT!


#ifndef ROSORBITCAMERA_MESSAGE_INT32NUMPY_H
#define ROSORBITCAMERA_MESSAGE_INT32NUMPY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosorbitcamera
{
template <class ContainerAllocator>
struct Int32Numpy_
{
  typedef Int32Numpy_<ContainerAllocator> Type;

  Int32Numpy_()
    : data()  {
    }
  Int32Numpy_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::rosorbitcamera::Int32Numpy_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosorbitcamera::Int32Numpy_<ContainerAllocator> const> ConstPtr;

}; // struct Int32Numpy_

typedef ::rosorbitcamera::Int32Numpy_<std::allocator<void> > Int32Numpy;

typedef boost::shared_ptr< ::rosorbitcamera::Int32Numpy > Int32NumpyPtr;
typedef boost::shared_ptr< ::rosorbitcamera::Int32Numpy const> Int32NumpyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosorbitcamera::Int32Numpy_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosorbitcamera::Int32Numpy_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosorbitcamera

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'rosorbitcamera': ['/home/andreea/Documents/catkin_ws/src/rosorbitcamera/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosorbitcamera::Int32Numpy_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosorbitcamera::Int32Numpy_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosorbitcamera::Int32Numpy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosorbitcamera::Int32Numpy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosorbitcamera::Int32Numpy_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosorbitcamera::Int32Numpy_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosorbitcamera::Int32Numpy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "563b27884d008b0d2adff54dc1f9e4f5";
  }

  static const char* value(const ::rosorbitcamera::Int32Numpy_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x563b27884d008b0dULL;
  static const uint64_t static_value2 = 0x2adff54dc1f9e4f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosorbitcamera::Int32Numpy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosorbitcamera/Int32Numpy";
  }

  static const char* value(const ::rosorbitcamera::Int32Numpy_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosorbitcamera::Int32Numpy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] data\n\
";
  }

  static const char* value(const ::rosorbitcamera::Int32Numpy_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosorbitcamera::Int32Numpy_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Int32Numpy_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosorbitcamera::Int32Numpy_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosorbitcamera::Int32Numpy_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSORBITCAMERA_MESSAGE_INT32NUMPY_H
